### ISSUE TITLE
Update for sensor.sickchill fails

### ISSUE THREAD

**Issue by Marcmk1** [youdroid/home-assistant-sickchill#16]
Update for sensor.sickchill fails

  - platform: sickchill
    name: sickchill
    token: !secret token-sc
    host: !secret host-sc
    port: 8081
    protocol: 'http'

Update for sensor.sickchill fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sickchill/sensor.py", line 86, in update
    ifs_tv_shows = self.get_infos(self.protocol, self.host, self.port, self.token, self.web_root, 'shows')
  File "/config/custom_components/sickchill/sensor.py", line 154, in get_infos
    ifs_movies = requests.get(url).json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Home Assistant 2021.2.3

Sickchill version
Branch: master
Commit: d76229cd404a162a707d189302990d8911ffe77e
Version: v2021.04.10-1
Database Version: 44.2

There are nog logs on SickChill

**Comment by youdroid** [comment]
Hi @Marcmk1,

Your problem comes from a call to the sickchill API to retrieve data from a series.

Before your probem everything worked fine? Have you recently added a TV series? 
If so, that's the problem with this TV shows !

**Comment by Marcmk1** [comment]
This is the first time I'm using the sensor.

This is a new installation with SickChill.
Only my data were imported from a back-up before updating SickChill.

Hmm, so which Serie is it :)
